title: Grav
default_lang: en
author:
  name: 'Al Chen'
  email: joe@example.com
taxonomies:
  - category
  - tag
  - author
metadata:
  description: 'Coda is a doc with magic tricks.'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
