enabled: true
production-mode: false
grid-size: grid-md
header-fixed: true
header-animated: true
header-dark: false
header-transparent: false
sticky-footer: true
blog-page: /blog
spectre:
  exp: false
  icons: false
custom_logo:
  user/themes/krypton/images/logo/coda-font-red.png:
    name: coda-font-red.png
    type: image/png
    size: 3568
    path: user/themes/krypton/images/logo/coda-font-red.png
